app:
  title: Developer Portal - Cluster
  baseUrl: ${BASE_URL}
  listen:
    host: 0.0.0.0 

backend:
  baseUrl: ${BASE_URL}
  listen:
    port: 7000
  database:
    client: better-sqlite3
    connection: ':memory:'
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # database:
  #   client: pg
  #   connection:
  #     host: ${POSTGRES_HOST}
  #     port: ${POSTGRES_PORT}
  #     user: ${POSTGRES_USER}
  #     password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt
      # prod Ov23liD2HfaLhyyUI2WJ / 9e7cdf7b1aa5a63d99821a9b178e2bfbd02ab407
auth:
  environment: production
  providers:
    gitlab:
      production:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        audience: ${AUDIENCE}
        callbackUrl: ${GITLAB_CALLBACK_URL}



integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      baseUrl: ${GITLAB_ONPREM_URL}
      apiBaseUrl: ${GITLAB_ONPREM_API_URL}
      token: ${GITLAB_TOKEN}


catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: /app/custom-template/springboot.yaml
      rules:
        - allow: [Template]

