app:
  title: Developer Portal - Local
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true


auth:
  environment: development
  providers:
    gitlab:
      development:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        
        

integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
  
      

catalog:
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: ../../custom-template/springboot.yaml
      rules:
        - allow: [Template]
