apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  # {{% if values.description%}}
  # description: ${{ values.description }}
  # {{% endif %}}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: ${{ values.groupId | dump}}
  lifecycle: experimental